### PR TITLE
Closes #75 adds chinese postman pgtap tests to check output after row ordering

### LINKED ISSUE #75: Ordering chinese postman
From #68 
Tasks
- add test
- if test fails then:
  - include comment in this issue what is the output and what is the expected result
  - Don't fix code, let it as todo (experimental function)
- if test pass do nothing else

### PR DESCRIPTION
**Pull request by krashish8**
Fixes #75 

Changes proposed in this pull request:
- Adds pgTAP tests for chinese postman that check the output after rows ordering.

@pgRouting/admins

### CODE REVIEW

File: pgtap/chinese/chinesePostman/chinesePostman-rows-check.sql [hunk 1]
```diff
@@ -30,11 +30,15 @@ SELECT * FROM pgr_chinesePostman(
     ORDER BY RANDOM()'
 );
 
+SELECT todo_start('Fix the code to return same set of rows');
```
Comment (cvvergara) [inline pgtap/chinese/chinesePostman/chinesePostman-rows-check.sql:33]: So lets refine:

SELECT todo_start('Chinese Postman Problem is Experimental, tests left pending');
