### PR TITLE
Closes #78 fixing breadthFirstSearch ordering issue

### LINKED ISSUE #78: Ordering breadthFirstSearch
From #68 
Tasks
- add test
- if test fails then:
  - include comment in this issue what is the output and what is the expected result
  - Don't fix code, let it as todo (experimental function)
- if test pass do nothing else

### PR DESCRIPTION
**Pull request by krashish8**
Fixes #78.

Changes proposed in this pull request:
- Adds pgTAP tests for breadthFirstSearch that check the output after rows ordering.
-
-

@pgRouting/admins

### CODE REVIEW

File: pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql [hunk 1]
```diff
@@ -0,0 +1,106 @@
+\i setup.sql
+
+SELECT plan(10);
+
+
+-- Check whether the same set of rows is always returned
+
+-- Creating the table used for the queries
+
+DROP TABLE IF EXISTS roadworks CASCADE;
```
Comment (cvvergara) [inline pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql:10]: Why do you need roadworks?
you are creating, inserting and not using that table in any of your tests.
please delete

Comment (krashish8) [reply pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql:10]: Oh sorry. I was supposed to use `roadworks` here instead of `edge_table` (based on the function's documentation)

Comment (cvvergara) [reply pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql:10]: Wrong, you have to use the edge_table

Comment (krashish8) [reply pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql:10]: I changed a lot of files in those 4-5 days (mainly copy-paste). That's why this error :(

Comment (cvvergara) [reply pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql:10]: The user's documentation will be fixed, they have to use the edge_table

File: src/breadthFirstSearch/breadthFirstSearch_driver.cpp [hunk 2]
```diff
@@ -88,10 +88,11 @@ do_pgr_breadthFirstSearch(
             start_vertices(start_vidsArr, start_vidsArr + size_start_vidsArr);
 
         std::vector<pgr_mst_rt> results;
+        std::string logstr;
```
Comment (krashish8) [inline src/breadthFirstSearch/breadthFirstSearch_driver.cpp:91]: I don't know how this came here...

Comment (krashish8) [reply src/breadthFirstSearch/breadthFirstSearch_driver.cpp:91]: Maybe I should sleep now... zZ (after this passes and squash & merged)
